name: Zig Package Update and Release
on:
  schedule:
    # Run every 1 days
    - cron: '0 0 */1 * *'
  workflow_dispatch:  # Allow manual triggering
# Add permission to create releases and push to the repository
permissions:
  contents: write
jobs:
  update-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup git for commits
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
      - name: Run updater in Docker
        run: |
          # Run the updater in an Arch Linux Docker container
          docker run --rm -v ${{ github.workspace }}:/work -w /work archlinux:latest bash -c "
            pacman -Syu --noconfirm
            pacman -S --noconfirm jq curl minisign ripgrep
            chmod +x ./updater.sh
            ./updater.sh
          "
          
          # Check for changes and commit if any - but continue either way
          if git diff --exit-code PKGBUILD; then
            echo "No changes detected in PKGBUILD, continuing with build"
          else
            echo "Changes detected in PKGBUILD, committing updates"
            
            # Commit the changes
            git add PKGBUILD
            git commit -m "Update Zig version from updater.sh"
            git push
          fi
          
          # Get current date for tagging
          echo "build_date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
        id: update
        
      - name: Build package in Docker
        run: |
          # Run makepkg in an Arch Linux Docker container
          docker run --rm -v ${{ github.workspace }}:/work -w /work archlinux:latest bash -c "
            pacman -Syu --noconfirm
            pacman -S --noconfirm base-devel sudo git jq curl minisign ripgrep
            
            # Create a non-root user for makepkg (it refuses to run as root)
            useradd -m builder
            chown -R builder:builder /work
            
            # Run makepkg as the builder user - removed --nocheck to ensure prepare() runs
            sudo -u builder bash -c 'cd /work && makepkg -f --skipinteg'
            
            # List all files to debug what was created
            echo 'Files created:'
            ls -la /work/
            echo 'Package files:'
            find /work -name '*.pkg.tar.*' -type f
          "
          
      - name: Delete previous release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          tag_name: latest
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create new release
        uses: softprops/action-gh-release@v1
        with:
          name: "Zig Package (Build ${{ steps.update.outputs.build_date }})"
          tag_name: latest
          files: |
            *.pkg.tar.*
          body: |
            Automated build of Zig package
            
            Build Date: ${{ steps.update.outputs.build_date }}
            Workflow Run: ${{ github.run_id }}
            Build triggered by: ${{ github.event_name }}
            
            ## Installation
            Download the `.pkg.tar.zst` file and install with:
            ```bash
            sudo pacman -U zig-dev-bin-*.pkg.tar.zst
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
